apiVersion: v1
kind: ServiceAccount
metadata:
  name: shareslices-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shareslices-maintenance
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shareslices-content
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shareslices-worker
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shareslices-web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shareslices-migrate
automountServiceAccountToken: false
