apiVersion: apps/v1
kind: Deployment
metadata:
  name: shareslices-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shareslices-web
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shareslices-content
spec:
  replicas: 2
