import {createHash,randomBytes,randomUUID} from "node:crypto";
import type{Pool}from"pg";

export type GalleryDownloadAsset=Readonly<{path:string;objectKey:string;sizeBytes:number;contentType:string}>;
export type GalleryDownloadAcceptance=Readonly<{leaseId:string;leaseToken:string;assets:readonly GalleryDownloadAsset[];fileName:string;expiresAt:Date}>;
export class GalleryDownloadError extends Error{constructor(readonly code:"not_found"|"gone"|"rate_limited"|"concurrency_limited"){super(code);}}

export class GalleryDownloadService{
 constructor(private readonly pool:Pool,private readonly instanceId:string,private readonly maxInstance=8,private readonly maxDeployment=64,private readonly maxDurationSeconds=300,private readonly rateLimit=30){}
 async accept(slug:string,sourceKey:string):Promise<GalleryDownloadAcceptance>{const client=await this.pool.connect();try{await client.query("begin");const digest=createHash("sha256").update(sourceKey).digest("hex");const consumed=Number((await client.query("select count(*) count from gallery_download_rate_evidence where source_key_digest=$1 and consumed_at>now()-interval '1 hour'",[digest])).rows[0]?.count??0);if(consumed>=this.rateLimit)throw new GalleryDownloadError("rate_limited");const counts=(await client.query("select count(*) filter(where instance_id=$1) instance_count,count(*) deployment_count from gallery_download_source_lease where state='active' and expires_at>now()",[this.instanceId])).rows[0];if(Number(counts.instance_count)>=this.maxInstance||Number(counts.deployment_count)>=this.maxDeployment)throw new GalleryDownloadError("concurrency_limited");const {rows}=await client.query(`select listing.id,listing.lifecycle_state,listing.review_state,listing.listing_revision,listing.artifact_id,revision.version_id,revision.public_title
   from gallery_listing listing left join gallery_listing_revision revision on revision.id=listing.current_revision_id where listing.opaque_slug=$1 for update of listing`,[slug]);const listing=rows[0];if(!listing)throw new GalleryDownloadError("not_found");if(listing.lifecycle_state==="withdrawn")throw new GalleryDownloadError("gone");const blocked=(await client.query(`select exists(select 1 from gallery_public_sharing_restriction where artifact_id=$1 and state='active') or exists(select 1 from gallery_artifact_takedown where artifact_id=$1 and state='active') blocked`,[listing.artifact_id])).rows[0]?.blocked===true;if(listing.lifecycle_state!=="listed"||!["clear","reviewing"].includes(listing.review_state)||blocked)throw new GalleryDownloadError("not_found");const assets=(await client.query(`select asset.path,asset.object_key,asset.size_bytes,asset.content_type from artifact_version version join content_bundle_asset asset on asset.bundle_id=version.content_bundle_id and asset.owner_user_id=version.owner_user_id where version.id=$1 and version.state='ready' order by asset.path`,[listing.version_id])).rows.map((row)=>({path:String(row.path),objectKey:String(row.object_key),sizeBytes:Number(row.size_bytes),contentType:String(row.content_type)}));if(!assets.length)throw new GalleryDownloadError("not_found");const leaseId=`gdownload_${randomUUID()}`;const leaseToken=randomBytes(32).toString("base64url");const expiresAt=new Date(Date.now()+this.maxDurationSeconds*1000);await client.query("insert into gallery_download_source_lease(id,listing_id,listing_revision,version_id,instance_id,lease_token_digest,expires_at) values($1,$2,$3,$4,$5,$6,$7)",[leaseId,listing.id,listing.listing_revision,listing.version_id,this.instanceId,createHash("sha256").update(leaseToken).digest("hex"),expiresAt]);await client.query("insert into gallery_download_rate_evidence(id,source_key_digest,privacy_delete_after) values($1,$2,now()+interval '30 days')",[`gdrate_${randomUUID()}`,digest]);await client.query("update gallery_listing_engagement set download_count=download_count+1,updated_at=now() where listing_id=$1",[listing.id]);await client.query("commit");return{leaseId,leaseToken,assets,fileName:safeName(listing.public_title),expiresAt};}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
 async finish(leaseId:string,leaseToken:string,outcome:"finished"|"aborted"):Promise<boolean>{const digest=createHash("sha256").update(leaseToken).digest("hex");const result=await this.pool.query("update gallery_download_source_lease set state=$3,ended_at=now() where id=$1 and lease_token_digest=$2 and state='active'",[leaseId,digest,outcome]);return result.rowCount===1;}
 async expire():Promise<number>{const result=await this.pool.query("update gallery_download_source_lease set state='expired',ended_at=now() where state='active' and expires_at<=now()");return result.rowCount??0;}
}
function safeName(value:string){return`${value.replaceAll(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"artifact"}.zip`;}
