import type { Pool } from "pg";

export type GalleryPublicCard=Readonly<{slug:string;title:string;description:string|null;tags:readonly string[];createdAt:string;creator:Readonly<{slug:string;displayName:string}>;cover:Readonly<{state:"placeholder"|"ready";url:string|null}>}>;
export type GalleryPublicPage=Readonly<{items:readonly GalleryPublicCard[];nextCursor:string|null}>;
export type GallerySourceAttribution=Readonly<{originalCreator:Readonly<{slug:string;displayName:string}>|null}>;
export type GalleryPublicListingResult=Readonly<{kind:"eligible";listing:GalleryPublicCard&Readonly<{sourceAttribution:GallerySourceAttribution|null}>}>|Readonly<{kind:"not_found"|"gone"}>;

type Mode="default"|"newest"|"featured"|"search"|"tag"|"creator";
export class PublicGalleryService{
  constructor(private readonly pool:Pool){}
  async list(input:Readonly<{mode:Mode;query?:string;cursor?:string;limit:number}>):Promise<GalleryPublicPage>{const cursor=decodeCursor(input.cursor);const values:unknown[]=[input.limit+1];let filter="";if(input.mode==="search"){values.push(`%${input.query??""}%`);filter=`and (revision.public_title ilike $2 or coalesce(revision.public_description,'') ilike $2 or profile.display_name ilike $2 or exists (select 1 from unnest(revision.tags) tag where tag ilike $2))`;}if(input.mode==="tag"){values.push((input.query??"").toLocaleLowerCase("en-US"));filter="and $2=any(revision.tags)";}if(input.mode==="creator"){values.push(input.query??"");filter="and profile.opaque_slug=$2";}const featured=input.mode==="featured";const primary=featured?"featured.position::text":"listing.created_at::text";if(cursor){values.push(cursor.primary,cursor.listingId);const p=values.length-1;filter+=featured?` and (featured.position>$${p} or (featured.position=$${p}::integer and listing.id>$${p+1}))`:` and (listing.created_at<$${p}::timestamptz or (listing.created_at=$${p}::timestamptz and listing.id<$${p+1}))`;}
    const join=featured?"join gallery_featured_position featured on featured.listing_id=listing.id":"left join gallery_featured_position featured on featured.listing_id=listing.id";const order=featured?"featured.position,listing.id":"listing.created_at desc,listing.id desc";
    const {rows}=await this.pool.query(`select listing.id,listing.opaque_slug,listing.created_at,revision.public_title,revision.public_description,revision.tags,profile.opaque_slug creator_slug,profile.display_name,cover.state cover_state,cover.object_key,${primary} primary_key
      from gallery_listing listing join gallery_listing_revision revision on revision.id=listing.current_revision_id join gallery_creator_profile profile on profile.id=listing.creator_profile_id ${join} left join gallery_cover cover on cover.id=revision.cover_id
      where listing.lifecycle_state='listed' and listing.review_state in ('clear','reviewing') and profile.retired_at is null
      and not exists(select 1 from gallery_public_sharing_restriction restriction where restriction.artifact_id=listing.artifact_id and restriction.state='active')
      and not exists(select 1 from gallery_artifact_takedown takedown where takedown.artifact_id=listing.artifact_id and takedown.state='active') ${filter} order by ${order} limit $1`,values);
    const more=rows.length>input.limit;const selected=rows.slice(0,input.limit);const items=selected.map(card);const last=selected.at(-1);return{items,nextCursor:more&&last?encodeCursor({primary:String(last.primary_key),listingId:String(last.id)}):null};}
  async listing(slug:string):Promise<GalleryPublicListingResult>{const {rows}=await this.pool.query(`select listing.*,revision.public_title,revision.public_description,revision.tags,profile.opaque_slug creator_slug,profile.display_name,profile.retired_at profile_retired_at,cover.state cover_state,cover.object_key,provenance.artifact_id provenance_artifact_id,original_profile.opaque_slug original_creator_slug,original_profile.display_name original_creator_display_name,original_profile.public_at original_creator_public_at,original_profile.retired_at original_creator_retired_at
    from gallery_listing listing left join gallery_listing_revision revision on revision.id=listing.current_revision_id join gallery_creator_profile profile on profile.id=listing.creator_profile_id left join gallery_cover cover on cover.id=revision.cover_id left join artifact_gallery_provenance provenance on provenance.artifact_id=listing.artifact_id left join gallery_creator_profile original_profile on original_profile.id=provenance.root_creator_profile_id where listing.opaque_slug=$1`,[slug]);const row=rows[0];if(!row)return{kind:"not_found"};if(row.lifecycle_state==="withdrawn")return{kind:"gone"};if(row.lifecycle_state!=="listed"||!(["clear","reviewing"] as const).includes(row.review_state)||row.profile_retired_at)return{kind:"not_found"};const blocked=(await this.pool.query(`select exists(select 1 from gallery_public_sharing_restriction where artifact_id=$1 and state='active') or exists(select 1 from gallery_artifact_takedown where artifact_id=$1 and state='active') blocked`,[row.artifact_id])).rows[0]?.blocked===true;if(blocked)return{kind:"not_found"};const originalCreator=row.original_creator_public_at&&!row.original_creator_retired_at?{slug:String(row.original_creator_slug),displayName:String(row.original_creator_display_name)}:null;return{kind:"eligible",listing:{...card(row),sourceAttribution:row.provenance_artifact_id?{originalCreator}:null}};}
  async creator(slug:string,cursor:string|undefined,limit:number):Promise<Readonly<{profile:{slug:string;displayName:string;biography:string|null;avatarUrl:string|null};listings:GalleryPublicPage}>|null>{const {rows}=await this.pool.query("select opaque_slug,display_name,biography,avatar_object_key,public_at,retired_at from gallery_creator_profile where opaque_slug=$1",[slug]);const row=rows[0];if(!row||!row.public_at||row.retired_at)return null;return{profile:{slug:row.opaque_slug,displayName:row.display_name,biography:row.biography,avatarUrl:row.avatar_object_key?`/gallery-media/avatar/${encodeURIComponent(row.opaque_slug)}`:null},listings:await this.list({mode:"creator",query:slug,...(cursor?{cursor}:{}),limit})};}
}
function card(row:Record<string,unknown>):GalleryPublicCard{return{slug:String(row.opaque_slug),title:String(row.public_title),description:row.public_description as string|null,tags:row.tags as string[],createdAt:(row.created_at as Date).toISOString(),creator:{slug:String(row.creator_slug),displayName:String(row.display_name)},cover:{state:row.cover_state==="ready"?"ready":"placeholder",url:row.cover_state==="ready"?`/gallery-media/cover/${encodeURIComponent(String(row.opaque_slug))}`:null}};}
function encodeCursor(value:{primary:string;listingId:string}){return Buffer.from(JSON.stringify(value)).toString("base64url");}function decodeCursor(value?:string):{primary:string;listingId:string}|null{if(!value)return null;try{const parsed=JSON.parse(Buffer.from(value,"base64url").toString("utf8"));return typeof parsed.primary==="string"&&typeof parsed.listingId==="string"?parsed:null;}catch{return null;}}
