apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/ingress
  - ../../components/gallery-isolation
  - ../../components/sizing-production
  - ../../components/network-policy
